# Generated by Django 6.0.2 on 2026-02-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], max_length=10)),
                ('description', models.TextField()),
                ('validateDeleteManager', models.BooleanField(default=False)),
                ('validateDeleteSuperAdmin', models.BooleanField(default=False)),
                ('isActiveReq', models.BooleanField(default=False)),
                ('viewDetails', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
